# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 6 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Search Updates
    - run: npm ci
    - run: node tarifas.js
    - name: Push updates
    - run: |
        git config --global user.name "Gunsha"
        git config --global user.email "gonzaller@gmail.com"
        git add .
        if ! git diff --cached --quiet; then
          git commit -m "Actualizando tarifas"
          git push
        else
          echo "No changes to commit."
        fi
